disabled_rules:
    - identifier_name
    - type_name

line_length:
  warning: 140
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true